### ISSUE TITLE
Нет доступа к репозиторию 

### ISSUE THREAD

**Issue by root1991** [st18rai/YalantisTask1#1]
Не могу запушить комментарии

**Comment by st18rai** [comment]
Вроде исправил

**Comment by root1991** [comment]
Всё ещё нет

**Comment by st18rai** [comment]
Извините, не работал с гитхабом, открылся доступ? Если нет, подскажите, где это настроить.

**Comment by root1991** [comment]
Settings -> Collaborators -> Нужно ввести root1991 и добавить
